services:
  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=task-manager
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      # Optional: add initialization script if needed
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - nx-network

  # Nx development service (contains both API and client)
  nx-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nx-workspace
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      # API port
      - "3333:3333" 
      # Client port (Angular/React)
      - "4200:4200"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://root:example@mongodb:27017/task-manager?authSource=admin
    command: npm run start-all
    depends_on:
      - mongodb
    networks:
      - nx-network

networks:
  nx-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
  node_modules: