version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=task-manager
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - app-network

  # Backend Express API service
  backend:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    container_name: backend
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=mongodb://task_user:task_password@mongodb:27017/task-manager
      - JWT_SECRET=your_secret_key_here
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - app-network

  # Frontend React application
  frontend:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    container_name: frontend
    restart: always
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://localhost:3000/api
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local